import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { FixedPlugin, Layout } from "@/components";

import localFont from "@next/font/local";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
  display: "swap",
});

const MITRE = localFont({
  src: [
    {
      path: "../../public/fonts/LincolnMITRE-LM5x7.otf",
      weight: "400",
    },
  ],
  variable: "--font-MITRE",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${MITRE.variable} font-sans`}>
      <body className={MITRE.variable}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
